### ISSUE TITLE
http dependency locked to old version

### ISSUE THREAD

**Issue by stephenhighemprise** [cloudinary/cloudinary_dart#68]
In my Flutter app, I'm using a newer version of the http package, but your API package is locked to an old version:

```
flutter pub get
Resolving dependencies...
Because every version of cloudinary_api depends on http ^0.13.5 and test_app depends on http ^1.1.0, cloudinary_api is forbidden.
So, because test_app depends on cloudinary_api ^1.0.0, version solving failed.
Process finished with exit code 1

```

I imagine there's no reason for your package to be locked to an old version of http, is there?  

By the way, I did downgrade my http package but then ran into this problem: 

`cloudinary_api ^1.0.0 which depends on cloudinary_url_gen ^0.10.0`

Since that url_gen package now has a 1.0 then you'd think cloudinary_api version 1.0 could use it.

**Comment by adimiz1** [comment]
Issue was resolved, please use version 1.0.2
