### ISSUE TITLE
Incorrect url generation for Gravity.southWest()

### ISSUE THREAD

**Issue by vadimbarda** [cloudinary/cloudinary_dart#73]
`Gravity.southWest()` generates to `g_southWest` in url and Cloudinary server returns 400. `Gravity.southWest()` should be `g_south_west` in url.

**Comment by PixelCook** [comment]
Hey there, 

Thanks for bringing this issue to our attention. We've added it to our sprint and you should see a fix soon. 

Cheers!

**Comment by adimiz1** [comment]
Issue was fixed on version 1.3.0, please re-open if you still have an issue.
