### ISSUE TITLE
Url generates open and close brackets

### ISSUE THREAD

**Issue by gd08xxx** [cloudinary/cloudinary_dart#96]
## Bug report for Cloudinary Dart SDK
Before proceeding, please update to latest version and test if the issue persists

## Describe the bug in a sentence or two.
…

## Issue Type (Can be multiple)
[ ] Build - Can’t install or import the SDK
[ ] Performance - Performance issues
[x] Behaviour - Functions aren’t working as expected (Such as generate URL)
[ ] Documentation - Inconsistency between the docs and behaviour
[ ] Other (Specify)

## Steps to reproduce
```cloudinary_url_gen: ^1.4.4```
when following steps similar to the example given in https://cloudinary.com/documentation/flutter_media_transformations#direct_url_building,
a pair of open and close brackets surrounds the url.
```
final String url = (
      cloudinary.image(publicId)
        ..transformation(
          Transformation()
            ..resize(
              Resize.fill()
                ..height('ih').aspectRatio(cld.AspectRatio.ar1X1())
                ..gravity(Gravity.autoGravity()),
            )
            ..delivery(Delivery.quality(Quality.autoBest()))
            ..delivery(Delivery.format(Format.webp)),
        ),
    ).toString();
```
The following error was shown in the console and the image cannot be shown.
```
The following FormatException was thrown resolving an image codec:
Scheme not starting with alphabetic character (at character 1)
(https://res.cloudinary.com/watchood/image/upload/ar_1:1,c_fill,g_auto,h_ih...
^
```
The following workaround solves the problem
```
final String url = (
      cloudinary.image(publicId)
        ..transformation(
          Transformation()
            ..resize(
              Resize.fill()
                ..height('ih').aspectRatio(cld.AspectRatio.ar1X1())
                ..gravity(Gravity.autoGravity()),
            )
            ..delivery(Delivery.quality(Quality.autoBest()))
            ..delivery(Delivery.format(Format.webp)),
        ),
    ).toString().replaceFirst('(', '').replaceFirst(')', '')
```
## Error screenshots or Stack Trace (if applicable)
…

## Build/Dependency management
[ ] Pubspec.yaml
[ ] Other (Specify)

## Is the issue reproducible only on a specific device?
[ x] No
[ ] Yes (specify device model + iOS/Android version)

## Versions and Libraries (fill in the version numbers)
Dart Cloudinary SDK version - 0.0.0
OS (on the dev environment) - 0.0.0 
IDE/Android Studio - 0.0.0

Repository
If possible, please provide a link to a reproducible repository that showcases the problem

**Comment by tommyg-cld** [comment]
@gd08xxx does the output also contain the transformations being used? can you paste the full output of the URL gen method please?

**Comment by tommyg-cld** [comment]
@gd08xxx speaking to our developer, this is how you are supposed to build the URL, comma is not meant to be used

`final String url = (cloudinary.image('test')..transformation(Transformation()..resize(Resize.fill()..height('ih').aspectRatio(AspectRatio.ar1X1())..gravity(Gravity.autoGravity()))..delivery(Delivery.quality(Quality.autoBest()))..delivery(Delivery.format(Format.webp)))).toString();`

let me know if this works

**Comment by gd08xxx** [comment]
Thanks, removing the comma worked. I'm strange that my IDE did not remind me this.
